server.port=8080
db.url=jdbc:mysql://localhost:3306/edusystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
db.username=root
db.password=
db.init-schema=false
